simplur: omit quantity
broofa/BroofaJS pull request #10
Opened 2020-10-07 16:15 UTC by rasgo-cc

This PR allows to omit the quantity on the output string.
The output of the `formatQuantity` function goes into the output string, so if an empty string or null or undefined are return, the quantity will be omitted in the output string. `trim()` was used to remove leading/trailing spaces after joining the results.

This is a breaking change tho, as with current code when `formatQuantity` function returns null, the quantity is not omitted.

Let me know what you think.

2020-10-07 19:24 UTC, broofa commented
* Rather than passing a `() => nulll` function, just omit the formatting function altogether to omit the quantity.  E.g.
```
simplur`${[1]}[This|These] [man|men]`  // => 'This man'
simplur`${[2]}[This|These] [man|men]`  // => 'These men'
```
* Change commit message to "fix: omit quantity, fixes #9"

2020-10-07 19:25 UTC, broofa requested changes

2020-10-07 19:25 UTC, broofa commented on simplur/index.js
> +  return result.join('').trim();
Revert.  Better to not make assumptions about what whitespace the caller  wants to include / exclude.

2020-10-08 09:40 UTC, rasgo-cc commented
Changes made, no need to pass the the `() => null` function to omit the quantity. I figured checking the number of arguments is unnecessary as we are checking the type for `a[1]` , which is undefined if it's not passed, so a one-liner can be used. Let me know what you think.

2020-10-10 14:05 UTC, broofa commented
Looks good, thanks!

2020-10-10 14:05 UTC, merged